export type CodexQuickConfigPlatform =
  | 'openai'
  | 'anthropic'
  | 'gemini'
  | 'antigravity'
  | 'grok'
  | 'kimi'
  | 'zhipu'
  | 'deepseek'
  | 'minimax'
  | 'opencode_go'
  | 'composite'

export interface CodexQuickConfigInput {
  apiKey: string
  baseUrl: string
  platform?: CodexQuickConfigPlatform | null
}

const preferredModels: Record<CodexQuickConfigPlatform, string> = {
  openai: 'gpt-5.5',
  anthropic: 'claude-sonnet-4-6',
  gemini: 'gemini-2.5-pro',
  antigravity: 'claude-sonnet-4-6',
  grok: 'grok-4.5',
  kimi: 'kimi-k2.5',
  zhipu: 'glm-4.7',
  deepseek: 'deepseek-v4-pro',
  minimax: 'MiniMax-M3',
  opencode_go: 'glm-5.3',
  composite: 'gpt-5.5'
}

const providerNames: Record<CodexQuickConfigPlatform, string> = {
  openai: 'OpenAI',
  anthropic: 'Sub2API Anthropic',
  gemini: 'Sub2API Gemini',
  antigravity: 'Sub2API Antigravity',
  grok: 'Sub2API Grok',
  kimi: 'Sub2API Kimi',
  zhipu: 'Sub2API Zhipu',
  deepseek: 'Sub2API DeepSeek',
  minimax: 'Sub2API MiniMax',
  opencode_go: 'Sub2API OpenCode',
  composite: 'Sub2API Composite'
}

function escapeTomlBasicString(value: string): string {
  return value
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\r/g, '\\r')
    .replace(/\n/g, '\\n')
}

export function normalizeCodexBaseUrl(baseUrl: string): string {
  const trimmed = baseUrl.trim().replace(/\/+$/, '')
  if (!trimmed) return ''
  return /\/v1$/i.test(trimmed) ? trimmed : `${trimmed}/v1`
}

export function buildCodexQuickConfigToml(input: CodexQuickConfigInput): string {
  const platform = input.platform || 'openai'
  const model = preferredModels[platform] || preferredModels.openai
  const provider = platform === 'openai' ? 'OpenAI' : 'sub2api'
  const providerName = providerNames[platform] || 'Sub2API'
  const baseUrl = normalizeCodexBaseUrl(input.baseUrl)

  return `# Generated by Sub2API. Re-running the setup script intentionally replaces this file.
model_provider = "${provider}"
model = "${escapeTomlBasicString(model)}"
review_model = "${escapeTomlBasicString(model)}"
disable_response_storage = true
network_access = "enabled"
windows_wsl_setup_acknowledged = true

[model_providers.${provider}]
name = "${escapeTomlBasicString(providerName)}"
base_url = "${escapeTomlBasicString(baseUrl)}"
wire_api = "responses"
requires_openai_auth = false
experimental_bearer_token = "${escapeTomlBasicString(input.apiKey)}"
http_headers = { "x-openai-actor-authorization" = "local-image-extension" }
supports_websockets = false

[features]
goals = true
`
}

export function encodeUtf8Base64(value: string): string {
  const bytes = new TextEncoder().encode(value)
  let binary = ''
  for (const byte of bytes) binary += String.fromCharCode(byte)
  return btoa(binary)
}

export function buildMacLinuxCodexQuickConfigScript(input: CodexQuickConfigInput): string {
  const payload = encodeUtf8Base64(buildCodexQuickConfigToml(input))
  return `#!/usr/bin/env bash
set -euo pipefail

CONFIG_DIR="${'${HOME}'}/.codex"
CONFIG_FILE="${'${CONFIG_DIR}'}/config.toml"
mkdir -p "${'${CONFIG_DIR}'}"
TMP_FILE="$(mktemp "${'${CONFIG_FILE}'}.tmp.XXXXXX")"
trap 'rm -f "${'${TMP_FILE}'}"' EXIT

PAYLOAD='${payload}'
if printf '%s' "${'${PAYLOAD}'}" | base64 --decode > "${'${TMP_FILE}'}" 2>/dev/null; then
  :
else
  printf '%s' "${'${PAYLOAD}'}" | base64 -D > "${'${TMP_FILE}'}"
fi

mv -f "${'${TMP_FILE}'}" "${'${CONFIG_FILE}'}"
trap - EXIT
printf 'Codex configuration written to %s\\n' "${'${CONFIG_FILE}'}"
`
}

export function buildWindowsCodexQuickConfigScript(input: CodexQuickConfigInput): string {
  const payload = encodeUtf8Base64(buildCodexQuickConfigToml(input))
  return `# Generated by Sub2API. Re-running the setup script intentionally replaces this file.
$ErrorActionPreference = 'Stop'

$configDir = Join-Path $env:USERPROFILE '.codex'
$configFile = Join-Path $configDir 'config.toml'
$tempFile = "$configFile.tmp.$([guid]::NewGuid().ToString('N'))"
$payload = '${payload}'

New-Item -ItemType Directory -Path $configDir -Force | Out-Null
try {
  [IO.File]::WriteAllBytes($tempFile, [Convert]::FromBase64String($payload))
  Move-Item -LiteralPath $tempFile -Destination $configFile -Force
} finally {
  if (Test-Path -LiteralPath $tempFile) {
    Remove-Item -LiteralPath $tempFile -Force -ErrorAction SilentlyContinue
  }
}

Write-Host "Codex configuration written to $configFile"
`
}
